version: "3.9"

volumes:
  postgres_data:
    driver: local

services:
  rs-postgres:
    image: postgres:latest
    container_name: rs-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: rsuser
      POSTGRES_PASSWORD: rspass

  rs-redis:
    restart: unless-stopped
    image: redis:latest
    container_name: rs-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
